version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    restart: always
    networks:
      new:
        aliases:
          - database
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}

  migrate:
    container_name: migrate-tool
    image: migrate/migrate
    networks:
      new:
    volumes:
      - ./migration:/migration
    command: ["-path", "/migration", "-database",  "postgres://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}?sslmode=disable", "up"]
    depends_on:
      - db

  rest:
    container_name: notes-rest-api
    restart: always
    build:
      context: ./
      dockerfile: ./docker/rest/Dockerfile
    ports:
      - "8080:${APP_PORT}"
    depends_on:
      - db
    env_file:
      - .env

networks:
  new: