version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    restart: always
    networks:
      new:
        aliases:
          - database
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  migrate:
    container_name: migrate-tool
    image: migrate/migrate
    networks:
      new:
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    links:
      - db
    depends_on:
      - db

  rest:
    container_name: notes-rest-api
    build: .
    command: ./main
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db

networks:
  new: